# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame_User(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(461, 328)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(50, 40, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.case_id = QtWidgets.QLineEdit(Frame)
        self.case_id.setGeometry(QtCore.QRect(180, 140, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.case_id.setFont(font)
        self.case_id.setObjectName("case_id")
        self.case_mdp = QtWidgets.QLineEdit(Frame)
        self.case_mdp.setGeometry(QtCore.QRect(180, 199, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.case_mdp.setFont(font)
        self.case_mdp.setObjectName("case_mdp")
        self.btn_se_connecter = QtWidgets.QPushButton(Frame)
        self.btn_se_connecter.setGeometry(QtCore.QRect(120, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn_se_connecter.setFont(font)
        self.btn_se_connecter.setObjectName("btn_se_connecter")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Bienvenu dans la version Python de notre PDL"))
        self.label_2.setText(_translate("Frame", "Identifiant : "))
        self.label_3.setText(_translate("Frame", "Mot de passe : "))
        self.btn_se_connecter.setText(_translate("Frame", "Se connecter"))
