# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'type_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(461, 328)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(130, 50, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_admin = QtWidgets.QPushButton(Frame)
        self.btn_admin.setGeometry(QtCore.QRect(60, 140, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_admin.setFont(font)
        self.btn_admin.setObjectName("btn_admin")
        self.btn_etudiant = QtWidgets.QPushButton(Frame)
        self.btn_etudiant.setGeometry(QtCore.QRect(60, 210, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_etudiant.setFont(font)
        self.btn_etudiant.setObjectName("btn_etudiant")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Authentification....."))
        self.btn_admin.setText(_translate("Frame", "Se connecter en tant qu\'administrateur"))
        self.btn_etudiant.setText(_translate("Frame", "Se connecter en tant qu\'étudiant"))
