-- création de la table administrateur

  CREATE TABLE "C##BDD8_7"."ADMIN" 
   (	"IDADMIN" NUMBER(20,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MOTDEPASSE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ADMIN_PK" PRIMARY KEY ("IDADMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ADMIN_UK1" UNIQUE ("MOTDEPASSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
-- creation de la table Dominante

  CREATE TABLE "C##BDD8_7"."DOMINANTE" 
   (	"IDDOM" NUMBER(2,0) NOT NULL ENABLE, 
	"NOMLONG" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SIGLE" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"PLACEMAX" NUMBER(2,0) NOT NULL ENABLE, 
	"PLACESAPPRENTIS" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "DOMINANTE_PK" PRIMARY KEY ("IDDOM")
  USING INDEX (CREATE UNIQUE INDEX "C##BDD8_7"."DOMINANTE_PK1" ON "C##BDD8_7"."DOMINANTE" ("IDDOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE, 
	 CONSTRAINT "DOMINANTE_CHK1" CHECK (PLACESAPPRENTIS < 12) ENABLE, 
	 CONSTRAINT "DOMINANTE_CHK2" CHECK (PLACEMAX < 35) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--création de la table filiere

  CREATE TABLE "C##BDD8_7"."FILIERE" 
   (	"IDFILIERE" NUMBER(1,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"NOMBRECHOIX" NUMBER, 
	 CONSTRAINT "FILIERE_PK" PRIMARY KEY ("IDFILIERE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  -- création de la table promotion
    CREATE TABLE "C##BDD8_7"."PROMOTION" 
   (	"IDPROMOTION" NUMBER(4,0) NOT NULL ENABLE, 
	"STATUT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PROMOTION_PK" PRIMARY KEY ("IDPROMOTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--création de la table Etudiant

  CREATE TABLE "C##BDD8_7"."ETUDIANT" 
   (	"IDETUDIANT" NUMBER(10,0) NOT NULL ENABLE, 
	"NOM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CLASSEMENT" NUMBER(4,0) NOT NULL ENABLE, 
	"MOTDEPASSE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDPROMOTION" NUMBER(4,0) NOT NULL ENABLE, 
	"IDFILIERE" NUMBER(2,0) NOT NULL ENABLE, 
	"IDDOMINANTE" NUMBER, 
	"DATENAISSANCE" DATE, 
	 CONSTRAINT "STUDENT_PK" PRIMARY KEY ("IDETUDIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ETUDIANT_CLASSEMENT_UNIQ" UNIQUE ("CLASSEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ETUDIANT_NOM_PRENOM_UNIQ" UNIQUE ("NOM", "PRENOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "IDPROMOTION_FK" FOREIGN KEY ("IDPROMOTION")
	  REFERENCES "C##BDD8_7"."PROMOTION" ("IDPROMOTION") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FILIERE_FK" FOREIGN KEY ("IDFILIERE")
	  REFERENCES "C##BDD8_7"."FILIERE" ("IDFILIERE") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  --creation de la table choix
  
  
  CREATE TABLE "C##BDD8_7"."CHOIX" 
   (	"NUMCHOIX" NUMBER(4,0) NOT NULL ENABLE, 
	"IDDOM" NUMBER(2,0) NOT NULL ENABLE, 
	"IDETUDIANT" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "CHOIX_PK" PRIMARY KEY ("IDDOM", "IDETUDIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "IDDOM_FK1" FOREIGN KEY ("IDDOM")
	  REFERENCES "C##BDD8_7"."DOMINANTE" ("IDDOM") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "IDETUDIANT_FK1" FOREIGN KEY ("IDETUDIANT")
	  REFERENCES "C##BDD8_7"."ETUDIANT" ("IDETUDIANT") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  -- insertion de données dans la table Administrateur
  INSERT INTO admin (IDADMIN, NOM, PRENOM, MOTDEPASSE) VALUES (
  6012006, 'BOCO', 'Hilary', 'AZE'
);
INSERT INTO admin (IDADMIN, NOM, PRENOM, MOTDEPASSE) VALUES (
  7062004, 'TOBOSSI', 'Junior', 'JUNIOR2.0'
);

-- insertion de données dans la table Dominante
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (1, 'Big Data pour la Transformation Numérique', 'BDTN', 30, 9);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (4, 'Ingénierie Financière', 'IF', 15, 2);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (6, 'Cybersécurité des Réseaux et de l''IOT', 'CERT', 15, 4);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (7, 'Ingénierie d''Affaires : Informatique et Réseaux', 'IA IR', 21, 3);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (8, 'Digitalisation Automatisation Robotique et Intelligence Artificielle pour l’industrie', 'DARIA', 12, 4);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (9, 'Energie et Développement Durable', 'EDD', 16, 4);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (10, 'Génie Electrique et Transport', 'GET', 17, 3);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (3, 'Intelligence Artificielle et Big Data', 'IABD', 18, 4);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (5, 'Ingénierie des Services du Numérique', 'ISN', 20, 4);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (11, 'Ingénieur d’Affaires Distribution Énergie et Signaux', 'IADES', 20, 2);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (12, 'Ingénierie des Systèmes Embarqués Mobiles Autonomes et Connectés', 'ISEMAC', 22, 3);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (13, 'Mécatronique et Systèmes Embarqués', 'MSE', 25, 3);
INSERT INTO Dominante (iddom, nomlong, sigle, placemax, placesapprentis) VALUES (14, 'Electronique des Systèmes pour l’Automobile et l’Aéronautique', 'ESAA', 16, 1);

--insertion dans la table filiere
INSERT INTO Filiere (idfiliere, nom, nombrechoix) VALUES (1, 'FISE', 5);
INSERT INTO Filiere (idfiliere, nom, nombrechoix) VALUES (2, 'FISA', 2);

--insertion dans la tabble promotion
INSERT INTO Promotion (idpromotion, statut) VALUES (2027, 1);

--insertion dans la table Etudiant
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (11646, 'Tate', 'Lilia', '23-10-2003', '21', 'LiliaTate92', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (12546, 'Haaland', 'Erling', '21-07-2000', '8', 'ErlingHaaland37', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (13098, 'Brooks', 'Chloe', '30-04-2003', '28', 'ChloeBrooks94', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (14264, 'Williams', 'Serena', '26-09-1981', '19', 'SerenaWilliams43', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (16972, 'Brown', 'StrangerThings', '06-02-2004', '50', 'StrangerThingsB99', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (35017, 'Rodrigo', 'Olivia', '20-02-2003', '4', 'OliviaRodrigo31', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (28919, 'West', 'North', '15-06-2013', '15', 'NorthWest23', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (64921, 'Grande', 'Ariana', '26-06-1993', '10', 'ArianaGrande84', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (22599, 'Beckham', 'Romeo', '01-09-2002', '22', 'RomeoBeckham27', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (25758, 'Mendes', 'Shawn', '08-08-1998', '3', 'ShawnMendes73', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (27274, 'Yousafzai', 'Malala', '12-07-1997', '26', 'MalalaYousafzai58', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (28766, 'Hadid', 'Bella', '09-10-1996', '17', 'BellaHadid82', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (30644, 'Efron', 'Zac', '18-10-1987', '13', 'ZacEfron92', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (36090, 'Fanning', 'Dakota', '23-02-1994', '23', 'DakotaFanning36', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (37111, 'Chalamet', 'Timothée', '27-12-1995', '7', 'TimotheeChalamet19', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (34738, 'Swift', 'Taylor', '13-12-1989', '11', 'TaylorSwift48', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (09940, 'Eilish', 'Finneas', '30-07-1997', '29', 'FinneasEilish66', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (23441, 'Musk', 'X AE A-Xii', '04-05-2020', '27', 'XAEMusk11', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (23542, 'Gomez', 'Selena', '22-07-1992', '6', 'SelenaGomez65', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (84644, 'Elba', 'Isan', '12-01-2002', '18', 'IsanElba34', 2025, 2);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (34747, 'Thee', 'Megan', '15-02-1995', '12', 'MeganThee64', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (64560, 'Smith', 'Jaden', '08-07-1998', '16', 'JadenSmith71', 2025, 1);
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (12802, 'Anthony', 'Alexis', 44, 'AlexisAnthony26', 2025, 2, null, '01-SEP-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (46746, 'Carter', 'Amy', 206, 'AmyCarter45', 2025, 2, null, '15-JAN-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (39398, 'West', 'Linda', 220, 'LindaWest10', 2025, 2, null, '28-OCT-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (75873, 'Burnett', 'Nancy', 215, 'NancyBurnett80', 2025, 2, null, '21-APR-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (49586, 'Lowe', 'Brian', 123, 'BrianLowe80', 2025, 2, null, '13-DEC-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (60329, 'Smith', 'Benjamin', 244, 'BenjaminSmith35', 2025, 2, null, '18-FEB-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (99249, 'Grimes', 'Thomas', 183, 'ThomasGrimes12', 2025, 2, null, '18-OCT-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (83258, 'George', 'Amanda', 72, 'AmandaGeorge37', 2025, 2, null, '14-MAR-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (80766, 'Mcneil', 'Craig', 63, 'CraigMcneil85', 2025, 2, null, '17-NOV-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (33810, 'Giles', 'Lauren', 154, 'LaurenGiles14', 2025, 2, null, '03-AUG-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (54879, 'Miles', 'Kara', 128, 'KaraMiles86', 2025, 2, null, '19-JUN-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (19691, 'Murphy', 'Richard', 253, 'RichardMurphy64', 2025, 2, null, '23-NOV-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (23766, 'Garcia', 'Thomas', 153, 'ThomasGarcia72', 2025, 2, null, '05-JUL-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (40224, 'Williams', 'Christine', 71, 'ChristineWilliams62', 2025, 2, null, '29-APR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (69898, 'Mendoza', 'Matthew', 246, 'MatthewMendoza43', 2025, 2, null, '07-FEB-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (71296, 'Miller', 'Carl', 197, 'CarlMiller42', 2025, 2, null, '26-FEB-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (10873, 'Massey', 'Jessica', 125, 'JessicaMassey13', 2025, 2, null, '12-DEC-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (97957, 'Ferguson', 'Renee', 190, 'ReneeFerguson90', 2025, 2, null, '02-AUG-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (12360, 'Navarro', 'Kevin', 251, 'KevinNavarro21', 2025, 2, null, '29-APR-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (12941, 'Johnson', 'Erin', 275, 'ErinJohnson52', 2025, 2, null, '10-APR-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (94086, 'Turner', 'Sherri', 135, 'SherriTurner61', 2025, 2, null, '06-SEP-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (48479, 'Stone', 'Lisa', 219, 'LisaStone81', 2025, 2, null, '28-OCT-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (63517, 'Wallace', 'Kimberly', 264, 'KimberlyWallace66', 2025, 2, null, '26-SEP-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (75784, 'Robinson', 'Ashley', 29, 'AshleyRobinson68', 2025, 2, null, '06-JUN-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21482, 'Williams', 'Jared', 144, 'JaredWilliams82', 2025, 2, null, '31-OCT-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (59361, 'Gillespie', 'Patricia', 221, 'PatriciaGillespie93', 2025, 2, null, '25-NOV-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (35923, 'Wilson', 'Kevin', 40, 'KevinWilson29', 2025, 2, null, '27-AUG-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (26137, 'Arnold', 'Daniel', 174, 'DanielArnold18', 2025, 2, null, '01-AUG-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (19163, 'Cook', 'Laura', 68, 'LauraCook95', 2025, 2, null, '20-MAY-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21778, 'Chang', 'Linda', 48, 'LindaChang46', 2025, 2, null, '16-MAY-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (95599, 'Mccann', 'Alejandro', 55, 'AlejandroMccann39', 2025, 1, null, '08-JUN-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (98072, 'Bradley', 'James', 22, 'JamesBradley49', 2025, 1, null, '11-AUG-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (92952, 'Wolfe', 'Dustin', 86, 'DustinWolfe76', 2025, 1, null, '04-DEC-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (10886, 'Miller', 'Cynthia', 193, 'CynthiaMiller72', 2025, 1, null, '26-MAR-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (75200, 'Fleming', 'David', 191, 'DavidFleming75', 2025, 1, null, '19-NOV-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (51325, 'Weiss', 'Clayton', 222, 'ClaytonWeiss30', 2025, 1, null, '20-MAY-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (91594, 'Douglas', 'Eduardo', 142, 'EduardoDouglas53', 2025, 1, null, '01-NOV-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (56152, 'White', 'Brandon', 236, 'BrandonWhite58', 2025, 1, null, '22-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (32971, 'Rubio', 'Sharon', 33, 'SharonRubio25', 2025, 1, null, '12-DEC-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (32852, 'Nunez', 'Jamie', 32, 'JamieNunez79', 2025, 1, null, '21-OCT-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (70449, 'Hooper', 'Mitchell', 146, 'MitchellHooper96', 2025, 1, null, '24-JUL-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (35912, 'Obrien', 'Cynthia', 100, 'CynthiaObrien17', 2025, 1, null, '21-FEB-07');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (25474, 'Campbell', 'Brandon', 216, 'BrandonCampbell76', 2025, 1, null, '21-JUN-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (36708, 'Clarke', 'Mathew', 243, 'MathewClarke53', 2025, 1, null, '15-APR-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (92403, 'Heath', 'Cameron', 62, 'CameronHeath84', 2025, 1, null, '07-NOV-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (78732, 'Lee', 'Aaron', 94, 'AaronLee78', 2025, 1, null, '17-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (42599, 'Frank', 'Patrick', 84, 'PatrickFrank96', 2025, 1, null, '04-SEP-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (46576, 'Villa', 'Bradley', 167, 'BradleyVilla60', 2025, 1, null, '11-APR-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (31425, 'Kirby', 'Sandra', 229, 'SandraKirby39', 2025, 1, null, '24-DEC-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (41788, 'Allen', 'Matthew', 61, 'MatthewAllen94', 2025, 1, null, '15-MAY-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (57792, 'Sandoval', 'Lauren', 69, 'LaurenSandoval33', 2025, 1, null, '16-JAN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (97700, 'York', 'Brenda', 200, 'BrendaYork41', 2025, 1, null, '22-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (85126, 'Sutton', 'Rachel', 77, 'RachelSutton78', 2025, 1, null, '27-MAY-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (43681, 'Hatfield', 'Edward', 180, 'EdwardHatfield33', 2025, 1, null, '05-SEP-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (95710, 'Griffin', 'Anthony', 74, 'AnthonyGriffin67', 2025, 1, null, '06-OCT-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (15781, 'Levy', 'Robin', 233, 'RobinLevy56', 2025, 1, null, '02-OCT-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (99875, 'Fowler', 'Terri', 189, 'TerriFowler18', 2025, 1, null, '18-JUN-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (23178, 'White', 'Michael', 138, 'MichaelWhite68', 2025, 1, null, '26-SEP-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (84945, 'Miller', 'Randy', 107, 'RandyMiller45', 2025, 1, null, '02-MAY-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (14897, 'Robinson', 'Chelsea', 255, 'ChelseaRobinson22', 2025, 1, null, '23-OCT-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (41532, 'Bowman', 'Raven', 126, 'RavenBowman81', 2025, 1, null, '15-JUN-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (53897, 'Turner', 'Kristen', 85, 'KristenTurner82', 2025, 1, null, '05-DEC-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (87249, 'Ortiz', 'Thomas', 99, 'ThomasOrtiz46', 2025, 1, null, '27-DEC-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (72075, 'Reed', 'Debra', 166, 'DebraReed53', 2025, 1, null, '06-JAN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (19576, 'Mays', 'Stacey', 108, 'StaceyMays19', 2025, 1, null, '29-DEC-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (60105, 'Reed', 'Andrea', 173, 'AndreaReed12', 2025, 1, null, '03-JUN-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (54643, 'Lopez', 'Michele', 91, 'MicheleLopez22', 2025, 1, null, '03-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (60624, 'Carr', 'Ryan', 145, 'RyanCarr92', 2025, 1, null, '07-APR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21374, 'Williams', 'Andrew', 238, 'AndrewWilliams44', 2025, 1, null, '13-JAN-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (65757, 'Romero', 'Ashley', 175, 'AshleyRomero79', 2025, 1, null, '02-NOV-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (63488, 'Hoffman', 'Tony', 155, 'TonyHoffman54', 2025, 1, null, '13-JAN-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (84863, 'Benton', 'John', 109, 'JohnBenton32', 2025, 1, null, '08-MAR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (81068, 'Long', 'Alan', 8, 'AlanLong52', 2025, 1, null, '13-AUG-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (82121, 'Bailey', 'Anthony', 192, 'AnthonyBailey30', 2025, 1, null, '19-MAR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (79039, 'Williamson', 'Antonio', 66, 'AntonioWilliamson30', 2025, 1, null, '04-JAN-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (13646, 'Jones', 'Kristine', 207, 'KristineJones57', 2025, 1, null, '30-MAY-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (20690, 'Howard', 'Chad', 156, 'ChadHoward91', 2025, 1, null, '11-FEB-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (47878, 'Hughes', 'Jennifer', 203, 'JenniferHughes22', 2025, 1, null, '27-JUL-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (37737, 'Cherry', 'Mary', 250, 'MaryCherry26', 2025, 1, null, '11-JAN-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (29493, 'Gray', 'Dana', 82, 'DanaGray85', 2025, 1, null, '27-MAR-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (20702, 'Roman', 'Jennifer', 259, 'JenniferRoman61', 2025, 1, null, '21-JAN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (54507, 'Garcia', 'Lisa', 204, 'LisaGarcia39', 2025, 1, null, '27-FEB-07');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (49255, 'Clark', 'David', 89, 'DavidClark74', 2025, 1, null, '26-AUG-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (10160, 'Williams', 'Paul', 242, 'PaulWilliams84', 2025, 1, null, '01-NOV-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (75743, 'Douglas', 'Chloe', 118, 'ChloeDouglas82', 2025, 1, null, '15-OCT-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (22153, 'Buck', 'David', 57, 'DavidBuck60', 2025, 1, null, '06-NOV-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (19928, 'Harrell', 'Mark', 184, 'MarkHarrell34', 2025, 1, null, '07-DEC-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (74832, 'Morales', 'Robert', 274, 'RobertMorales34', 2025, 1, null, '29-SEP-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (48914, 'Barnes', 'Jacqueline', 158, 'JacquelineBarnes69', 2025, 1, null, '15-MAY-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (59260, 'Lucas', 'Jeffrey', 141, 'JeffreyLucas38', 2025, 1, null, '12-FEB-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (47312, 'Foster', 'Keith', 43, 'KeithFoster41', 2025, 1, null, '26-FEB-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (80510, 'Carter', 'Thomas', 160, 'ThomasCarter63', 2025, 1, null, '26-MAR-07');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (85304, 'Smith', 'Jennifer', 261, 'JenniferSmith87', 2025, 1, null, '17-SEP-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (78809, 'Kramer', 'Christy', 120, 'ChristyKramer54', 2025, 1, null, '21-JUN-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (16282, 'Morrison', 'Tamara', 46, 'TamaraMorrison49', 2025, 1, null, '14-APR-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (68873, 'Becker', 'Monique', 217, 'MoniqueBecker97', 2025, 1, null, '12-MAR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (77894, 'Cox', 'Tammy', 227, 'TammyCox88', 2025, 1, null, '19-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (62828, 'Sanchez', 'Mikayla', 129, 'MikaylaSanchez58', 2025, 1, null, '06-SEP-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (75344, 'Oliver', 'Cynthia', 267, 'CynthiaOliver91', 2025, 1, null, '30-DEC-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (61708, 'Ponce', 'John', 122, 'JohnPonce37', 2025, 1, null, '16-MAY-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (94826, 'Hinton', 'Edward', 224, 'EdwardHinton84', 2025, 1, null, '06-SEP-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (56094, 'Jones', 'Alexandra', 263, 'AlexandraJones54', 2025, 1, null, '28-DEC-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (23574, 'Curtis', 'Robert', 235, 'RobertCurtis11', 2025, 1, null, '07-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (89696, 'Ibarra', 'Tracy', 1, 'TracyIbarra95', 2025, 1, null, '11-APR-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (88079, 'Howard', 'James', 273, 'JamesHoward14', 2025, 1, null, '28-APR-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (96278, 'Martinez', 'Shawna', 60, 'ShawnaMartinez28', 2025, 1, null, '16-MAR-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (54721, 'King', 'Christine', 96, 'ChristineKing53', 2025, 1, null, '30-JAN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (19617, 'Meyers', 'Rachel', 92, 'RachelMeyers32', 2025, 1, null, '10-JUL-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (78064, 'Williams', 'William', 130, 'WilliamWilliams89', 2025, 1, null, '11-MAR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (24941, 'Sanders', 'David', 177, 'DavidSanders48', 2025, 1, null, '30-APR-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (29113, 'Shaw', 'Rachel', 80, 'RachelShaw87', 2025, 1, null, '13-FEB-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (82813, 'Lewis', 'Stacy', 110, 'StacyLewis28', 2025, 1, null, '19-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (15784, 'Hernandez', 'Austin', 245, 'AustinHernandez71', 2025, 1, null, '26-MAR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (38916, 'Sullivan', 'William', 112, 'WilliamSullivan68', 2025, 1, null, '19-OCT-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (72336, 'Carlson', 'John', 195, 'JohnCarlson77', 2025, 1, null, '10-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (50062, 'Rice', 'Mackenzie', 266, 'MackenzieRice27', 2025, 1, null, '27-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (22761, 'Callahan', 'Laura', 254, 'LauraCallahan58', 2025, 1, null, '24-NOV-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (90281, 'Burgess', 'Vicki', 143, 'VickiBurgess85', 2025, 1, null, '10-JUN-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (98535, 'Harris', 'Rebecca', 131, 'RebeccaHarris54', 2025, 1, null, '03-AUG-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (77413, 'Olson', 'Margaret', 212, 'MargaretOlson63', 2025, 1, null, '13-NOV-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (72756, 'Fisher', 'Holly', 179, 'HollyFisher93', 2025, 1, null, '08-APR-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (41876, 'Morgan', 'Cynthia', 103, 'CynthiaMorgan42', 2025, 1, null, '26-AUG-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (85468, 'Nash', 'Craig', 228, 'CraigNash86', 2025, 1, null, '09-APR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (94420, 'Myers', 'Amber', 257, 'AmberMyers92', 2025, 1, null, '18-JAN-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (56903, 'Thompson', 'Scott', 241, 'ScottThompson72', 2025, 1, null, '11-JAN-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (13178, 'Simpson', 'Natalie', 187, 'NatalieSimpson10', 2025, 1, null, '30-JUN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (11712, 'Payne', 'Nicholas', 119, 'NicholasPayne93', 2025, 1, null, '22-SEP-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (63010, 'Howard', 'Ryan', 90, 'RyanHoward93', 2025, 1, null, '27-MAR-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (50456, 'Mcdonald', 'Chelsea', 78, 'ChelseaMcdonald13', 2025, 1, null, '20-NOV-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (34694, 'Green', 'Robert', 73, 'RobertGreen82', 2025, 1, null, '28-SEP-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (63316, 'Wallace', 'Briana', 211, 'BrianaWallace78', 2025, 1, null, '16-SEP-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (71215, 'Miller', 'Laura', 248, 'LauraMiller20', 2025, 1, null, '23-AUG-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21883, 'Cantu', 'William', 81, 'WilliamCantu95', 2025, 1, null, '20-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (96983, 'Rogers', 'Judith', 213, 'JudithRogers77', 2025, 1, null, '12-JUN-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (12168, 'Brown', 'Kara', 116, 'KaraBrown81', 2025, 1, null, '15-APR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (27472, 'Stark', 'Wendy', 163, 'WendyStark32', 2025, 1, null, '23-JUL-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (65485, 'Kelley', 'Jasmine', 114, 'JasmineKelley98', 2025, 1, null, '11-OCT-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (26115, 'Medina', 'Nathan', 47, 'NathanMedina19', 2025, 1, null, '11-DEC-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21959, 'Good', 'Joshua', 50, 'JoshuaGood95', 2025, 1, null, '09-AUG-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (94959, 'Carr', 'Robert', 164, 'RobertCarr15', 2025, 1, null, '07-APR-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (79340, 'Key', 'Jacob', 188, 'JacobKey41', 2025, 1, null, '11-JUN-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (51422, 'Peterson', 'Megan', 104, 'MeganPeterson47', 2025, 1, null, '25-AUG-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (76473, 'Henderson', 'Erin', 168, 'ErinHenderson11', 2025, 1, null, '26-SEP-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (95654, 'Estes', 'Matthew', 196, 'MatthewEstes52', 2025, 1, null, '01-NOV-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (25685, 'Miller', 'Cameron', 172, 'CameronMiller29', 2025, 1, null, '17-MAR-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (40763, 'Roberts', 'Michael', 178, 'MichaelRoberts57', 2025, 1, null, '19-APR-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (36701, 'Gregory', 'Audrey', 117, 'AudreyGregory31', 2025, 1, null, '19-AUG-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21940, 'Lamb', 'Steven', 59, 'StevenLamb35', 2025, 1, null, '16-JAN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (90131, 'Garcia', 'Crystal', 161, 'CrystalGarcia41', 2025, 1, null, '17-FEB-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (32807, 'Cooper', 'Daniel', 25, 'DanielCooper78', 2025, 1, null, '11-AUG-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (39797, 'Roberts', 'Barbara', 170, 'BarbaraRoberts62', 2025, 1, null, '29-MAY-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (43034, 'Estrada', 'Shirley', 234, 'ShirleyEstrada50', 2025, 1, null, '09-APR-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (56351, 'Collins', 'Troy', 226, 'TroyCollins36', 2025, 1, null, '02-SEP-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (33153, 'King', 'Mary', 14, 'MaryKing64', 2025, 1, null, '03-SEP-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (20846, 'Aguilar', 'Megan', 30, 'MeganAguilar87', 2025, 1, null, '07-SEP-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (33913, 'Chan', 'Pamela', 98, 'PamelaChan33', 2025, 1, null, '24-DEC-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (48825, 'Snyder', 'Aaron', 88, 'AaronSnyder62', 2025, 1, null, '28-DEC-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (35255, 'Williams', 'Eileen', 51, 'EileenWilliams97', 2025, 1, null, '05-DEC-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (75942, 'Jacobs', 'Angel', 198, 'AngelJacobs24', 2025, 1, null, '28-APR-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (71318, 'Boyer', 'Caleb', 232, 'CalebBoyer79', 2025, 1, null, '26-DEC-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (68724, 'Nunez', 'Jennifer', 36, 'JenniferNunez99', 2025, 1, null, '25-JUL-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (86445, 'Hill', 'Janet', 223, 'JanetHill32', 2025, 1, null, '10-NOV-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (71659, 'Carroll', 'Nancy', 269, 'NancyCarroll96', 2025, 1, null, '31-DEC-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (92084, 'Wells', 'Regina', 225, 'ReginaWells41', 2025, 1, null, '29-JUN-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (78321, 'Rivers', 'Samantha', 186, 'SamanthaRivers17', 2025, 1, null, '10-NOV-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (78339, 'Leblanc', 'Rachael', 4, 'RachaelLeblanc13', 2025, 1, null, '19-OCT-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (78599, 'Mcgrath', 'Renee', 93, 'ReneeMcgrath45', 2025, 1, null, '25-FEB-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (31840, 'Henson', 'Karla', 101, 'KarlaHenson59', 2025, 1, null, '07-APR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (37340, 'Lewis', 'Leslie', 231, 'LeslieLewis19', 2025, 1, null, '09-OCT-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (99621, 'Scott', 'William', 102, 'WilliamScott67', 2025, 1, null, '28-JUL-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (26754, 'Flores', 'Christopher', 9, 'ChristopherFlores53', 2025, 1, null, '18-MAY-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (66130, 'Butler', 'Barry', 278, 'BarryButler27', 2025, 1, null, '02-NOV-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (22009, 'Hernandez', 'Thomas', 150, 'ThomasHernandez24', 2025, 1, null, '01-FEB-07');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (49239, 'Smith', 'Ana', 31, 'AnaSmith52', 2025, 1, null, '28-SEP-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (31365, 'Coleman', 'Andrew', 95, 'AndrewColeman16', 2025, 1, null, '26-AUG-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (79110, 'Chang', 'Megan', 201, 'MeganChang71', 2025, 1, null, '03-NOV-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (39437, 'Ramirez', 'Monica', 106, 'MonicaRamirez90', 2025, 1, null, '15-OCT-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (16618, 'Williams', 'Renee', 162, 'ReneeWilliams48', 2025, 1, null, '01-AUG-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (64509, 'Gregory', 'Richard', 139, 'RichardGregory22', 2025, 1, null, '22-SEP-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (40784, 'Russo', 'Debra', 240, 'DebraRusso11', 2025, 1, null, '31-AUG-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (80846, 'Hernandez', 'Tonya', 182, 'TonyaHernandez78', 2025, 1, null, '07-SEP-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (98641, 'Tucker', 'Chloe', 256, 'ChloeTucker98', 2025, 1, null, '27-MAY-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (63590, 'Morris', 'Sally', 41, 'SallyMorris58', 2025, 1, null, '22-FEB-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (32058, 'Jimenez', 'Vernon', 252, 'VernonJimenez19', 2025, 1, null, '17-SEP-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (44161, 'Berry', 'Brandon', 39, 'BrandonBerry75', 2025, 1, null, '05-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (63454, 'Boyer', 'Travis', 35, 'TravisBoyer27', 2025, 1, null, '18-JAN-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (24059, 'Miller', 'Jennifer', 279, 'JenniferMiller92', 2025, 1, null, '12-OCT-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (17781, 'Lopez', 'Jaime', 97, 'JaimeLopez85', 2025, 1, null, '27-FEB-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (89062, 'Mueller', 'Jonathan', 271, 'JonathanMueller53', 2025, 1, null, '03-OCT-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (10294, 'Santana', 'Todd', 147, 'ToddSantana79', 2025, 1, null, '28-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (46704, 'Waters', 'Jose', 140, 'JoseWaters10', 2025, 1, null, '19-NOV-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (55905, 'Barrera', 'Lisa', 265, 'LisaBarrera85', 2025, 1, null, '10-SEP-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21203, 'Stark', 'Lauren', 87, 'LaurenStark70', 2025, 1, null, '26-JUL-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (25535, 'Trujillo', 'Jorge', 209, 'JorgeTrujillo92', 2025, 1, null, '18-NOV-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (47414, 'Gibson', 'Katherine', 75, 'KatherineGibson26', 2025, 1, null, '13-DEC-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (47974, 'Walls', 'Sandra', 42, 'SandraWalls47', 2025, 1, null, '18-DEC-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (73090, 'Jones', 'Lori', 133, 'LoriJones47', 2025, 1, null, '18-AUG-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (69933, 'Rose', 'Eric', 37, 'EricRose89', 2025, 1, null, '30-SEP-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (16851, 'Gonzalez', 'Dustin', 132, 'DustinGonzalez34', 2025, 1, null, '09-JAN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (77578, 'Davidson', 'Bryan', 194, 'BryanDavidson80', 2025, 1, null, '04-JUN-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (74538, 'Morgan', 'Jennifer', 52, 'JenniferMorgan27', 2025, 1, null, '04-FEB-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (29362, 'Barnett', 'Mallory', 277, 'MalloryBarnett99', 2025, 1, null, '10-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (47497, 'Riley', 'Stephanie', 111, 'StephanieRiley48', 2025, 1, null, '07-JUN-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (10485, 'Meyer', 'Dennis', 38, 'DennisMeyer82', 2025, 1, null, '05-AUG-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (33598, 'Richards', 'Tracy', 121, 'TracyRichards38', 2025, 1, null, '23-APR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (71115, 'Bennett', 'Courtney', 258, 'CourtneyBennett57', 2025, 1, null, '10-MAR-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (77505, 'Williams', 'Jeffrey', 67, 'JeffreyWilliams62', 2025, 1, null, '14-APR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (62397, 'Allen', 'Timothy', 214, 'TimothyAllen46', 2025, 1, null, '04-JUL-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21692, 'Anderson', 'Susan', 136, 'SusanAnderson71', 2025, 1, null, '03-SEP-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (91058, 'Blair', 'Kyle', 113, 'KyleBlair72', 2025, 1, null, '15-APR-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (28190, 'Myers', 'Barbara', 210, 'BarbaraMyers37', 2025, 1, null, '29-MAR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (17292, 'Price', 'Kylie', 5, 'KyliePrice71', 2025, 1, null, '12-JUN-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (34436, 'Knight', 'Ronald', 152, 'RonaldKnight51', 2025, 1, null, '08-JAN-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (95208, 'Leach', 'Jacqueline', 49, 'JacquelineLeach37', 2025, 1, null, '11-DEC-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (94208, 'Howard', 'Larry', 115, 'LarryHoward41', 2025, 1, null, '20-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (69467, 'White', 'Aaron', 262, 'AaronWhite82', 2025, 1, null, '10-APR-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (68765, 'Matthews', 'Jared', 124, 'JaredMatthews42', 2025, 1, null, '20-AUG-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (44005, 'Chavez', 'Joshua', 280, 'JoshuaChavez85', 2025, 1, null, '13-APR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (35804, 'Martin', 'Mark', 276, 'MarkMartin43', 2025, 1, null, '29-JUL-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (51896, 'Arroyo', 'Michael', 58, 'MichaelArroyo85', 2025, 1, null, '16-OCT-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (52637, 'Campos', 'Juan', 79, 'JuanCampos56', 2025, 1, null, '11-FEB-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (96887, 'West', 'April', 249, 'AprilWest73', 2025, 1, null, '26-APR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (17406, 'Dennis', 'John', 208, 'JohnDennis97', 2025, 1, null, '02-JUN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (98850, 'Cruz', 'Caitlyn', 165, 'CaitlynCruz33', 2025, 1, null, '03-MAR-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (74149, 'Wilson', 'Connor', 169, 'ConnorWilson92', 2025, 1, null, '12-JUL-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (91054, 'Hatfield', 'Jessica', 230, 'JessicaHatfield31', 2025, 1, null, '19-DEC-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (70228, 'Harris', 'Elizabeth', 134, 'ElizabethHarris50', 2025, 1, null, '14-JUN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (34357, 'Mitchell', 'David', 199, 'DavidMitchell58', 2025, 1, null, '21-OCT-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (91479, 'Wagner', 'Rebecca', 56, 'RebeccaWagner88', 2025, 1, null, '10-OCT-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (36299, 'Williams', 'Misty', 34, 'MistyWilliams37', 2025, 1, null, '14-JAN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (21518, 'Robinson', 'Dave', 65, 'DaveRobinson60', 2025, 1, null, '24-OCT-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (40875, 'Garcia', 'Robert', 159, 'RobertGarcia15', 2025, 1, null, '22-JUN-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (74388, 'Wood', 'Adrian', 185, 'AdrianWood80', 2025, 1, null, '07-AUG-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (20478, 'Clark', 'Patricia', 24, 'PatriciaClark74', 2025, 1, null, '23-JUN-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (53024, 'Frazier', 'Richard', 2, 'RichardFrazier84', 2025, 1, null, '15-SEP-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (50984, 'Lopez', 'Kristen', 202, 'KristenLopez55', 2025, 1, null, '22-OCT-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (62466, 'Wagner', 'Tanya', 21, 'TanyaWagner43', 2025, 1, null, '17-JUL-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (63412, 'Lawrence', 'Patty', 181, 'PattyLawrence84', 2025, 1, null, '04-FEB-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (87123, 'Grant', 'Erin', 151, 'ErinGrant31', 2025, 1, null, '24-JUN-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (82981, 'Patrick', 'Ricky', 64, 'RickyPatrick11', 2025, 1, null, '14-APR-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (14204, 'Holden', 'Frank', 76, 'FrankHolden15', 2025, 1, null, '09-APR-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (28217, 'Brown', 'Maria', 148, 'MariaBrown16', 2025, 1, null, '02-AUG-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (36196, 'Bruce', 'Crystal', 70, 'CrystalBruce43', 2025, 1, null, '26-OCT-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (56039, 'Lopez', 'Susan', 272, 'SusanLopez11', 2025, 1, null, '07-MAY-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (43032, 'Smith', 'Ann', 247, 'AnnSmith29', 2025, 1, null, '17-JUN-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (88124, 'Silva', 'Thomas', 237, 'ThomasSilva72', 2025, 1, null, '28-SEP-03');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (39948, 'Davis', 'Thomas', 54, 'ThomasDavis20', 2025, 1, null, '29-OCT-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (92483, 'Keller', 'Shannon', 26, 'ShannonKeller69', 2025, 1, null, '07-FEB-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (51875, 'Mcdowell', 'Katherine', 149, 'KatherineMcdowell29', 2025, 1, null, '21-AUG-06');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (82068, 'Hernandez', 'Alan', 260, 'AlanHernandez60', 2025, 1, null, '14-DEC-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (85814, 'Johnson', 'Gina', 270, 'GinaJohnson20', 2025, 1, null, '05-FEB-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (54599, 'Hinton', 'Micheal', 218, 'MichealHinton42', 2025, 1, null, '28-JUL-05');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (12015, 'Levy', 'Emily', 83, 'EmilyLevy25', 2025, 1, null, '15-FEB-07');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (35346, 'Atkinson', 'Lisa', 20, 'LisaAtkinson97', 2025, 1, null, '13-DEC-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (64851, 'Simmons', 'Holly', 176, 'HollySimmons66', 2025, 1, null, '15-AUG-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (74866, 'Joseph', 'Diana', 105, 'DianaJoseph29', 2025, 1, null, '25-APR-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (49696, 'Green', 'Craig', 127, 'CraigGreen38', 2025, 1, null, '02-MAY-02');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (19384, 'Rhodes', 'Shannon', 239, 'ShannonRhodes92', 2025, 1, null, '11-AUG-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (95321, 'Navarro', 'Kim', 205, 'KimNavarro81', 2025, 1, null, '31-MAR-00');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (60414, 'Fernandez', 'Lisa', 157, 'LisaFernandez25', 2025, 1, null, '16-JUL-04');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (45240, 'Ross', 'Jennifer', 137, 'JenniferRoss65', 2025, 1, null, '17-APR-99');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (45133, 'Jackson', 'Samantha', 268, 'SamanthaJackson90', 2025, 1, null, '23-JUL-01');
INSERT INTO ETUDIANT (IDETUDIANT, NOM, PRENOM, CLASSEMENT, MOTDEPASSE, IDPROMOTION, IDFILIERE, IDDOMINANTE, DATENAISSANCE) VALUES (89750, 'Green', 'Sean', 171, 'SeanGreen64', 2025, 1, null, '08-SEP-06');

--insertion dans la table choix
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (1, 7, 21482);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (2, 4, 21482);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (3, 9, 99249);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (4, 3, 99249);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (5, 12, 97957);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (6, 7, 97957);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (7, 9, 94086);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (8, 14, 94086);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (9, 8, 85126);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (10, 5, 85126);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (11, 14, 84644);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (12, 13, 84644);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (13, 12, 83258);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (14, 11, 83258);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (15, 3, 80766);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (16, 1, 80766);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (17, 5, 75873);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (18, 10, 75873);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (19, 10, 75784);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (20, 9, 75784);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (21, 9, 75743);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (22, 12, 75743);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (23, 5, 71296);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (24, 7, 71296);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (25, 10, 69898);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (26, 4, 69898);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (27, 8, 64921);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (28, 6, 64921);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (29, 6, 64851);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (30, 13, 64851);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (31, 6, 63517);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (32, 2, 63517);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (33, 3, 60329);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (34, 13, 60329);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (35, 6, 59361);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (36, 3, 59361);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (37, 3, 49586);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (38, 7, 49586);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (39, 5, 48479);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (40, 2, 48479);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (41, 11, 46746);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (42, 1, 46746);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (43, 11, 12802);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (44, 10, 12802);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (45, 3, 13646);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (46, 4, 13646);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (47, 10, 19163);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (48, 9, 19163);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (49, 10, 19691);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (50, 5, 19691);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (51, 11, 21778);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (52, 5, 21778);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (53, 6, 23441);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (54, 2, 23441);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (55, 14, 23766);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (56, 8, 23766);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (57, 4, 25758);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (58, 13, 25758);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (59, 12, 26137);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (60, 13, 26137);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (61, 3, 28919);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (62, 9, 28919);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (63, 8, 30644);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (64, 6, 30644);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (65, 11, 33810);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (66, 9, 33810);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (67, 5, 35923);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (68, 10, 35923);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (69, 5, 38916);
INSERT INTO choix (NUMCHOIX, IDDOM, IDETUDIANT) VALUES (70, 6, 38916);


